from enum import Enum


class Instructions(Enum):
    REGISTER_USER = "register_user"
    LOGIN_USER = "login_user"
    CREATE_AVATAR = "create_avatar"
    CLIENT_ALL_AVATARS = "client_all_avatars"
    CREATE_WORLD = "create_world"
    JOIN_WORLD = "join_world"
    WORLD_ALL_AVATARS = "world_all_avatars"
    SEND_MSG = "send_msg"
    SERVER_KEY = "server_key"
    CLIENT_KEY = "client_key"
    AVATAR_KEY = "avatar_key"
    GET_CLIENT_KEY = "get_client_key"
    ALL_WORLDS = "all_worlds"
    ENCRYPT_MSG = "encrypt_msg"
    DECRYPT_MSG = "decrypt_msg"
    GENERATE_KEY = "generate_key"
    
class Keys(Enum):
    MSG_TYPE = "msg_type"
    INSTRUCTION = "instruction"
    ERROR = "error"
    MESSAGE = "msg"
    WORLD_ID = "world_id"
    WORLD_NAME = "world_name"
    WORLD_VIEW_ID = "world_view_id"
    AVATAR_ID = "avatar_id"
    AVATAR_NAME = "avatar_name"
    AVATAR_VIEW_ID = "avatar_view_id"
    RECIEVER_ID = "receiver_id"
    PUBLIC_KEY = "public_key"
    PRIVATE_KEY = "private_key"
    ENCAPSULATED_KEY = "encapsulated_key"
    TAG = "tag"
    CIPHER_TEXT = "cipher_text"
    NONCE = "nonce"
    REGISTRATION_INFO = "registration_info"
    LOGIN_INFO = "login_info"
    USER_ID = "user_id"
    FIRST_NAME = "first_name"
    LAST_NAME = "last_name"
    USER_NAME = "user_name"
    PASSWORD = "password"
    
class MessageType(Enum):
    PLAIN_TEXT = "plain_text"
    ENCRYPTED_TEXT = "encrypted_text"